"""empty message

Revision ID: 02af933f1976
Revises: 5f22943f00a1
Create Date: 2020-04-03 17:40:40.391861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02af933f1976'
down_revision = '5f22943f00a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet', 'uuid')
    # ### end Alembic commands ###
