"""empty message

Revision ID: 0a90081923de
Revises: 0aedea0da459
Create Date: 2020-05-18 18:36:38.684766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a90081923de'
down_revision = '0aedea0da459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_name', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet', schema=None) as batch_op:
        batch_op.drop_column('show_name')

    # ### end Alembic commands ###
