"""empty message

Revision ID: 0aedea0da459
Revises: 02af933f1976
Create Date: 2020-04-13 20:34:35.030938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aedea0da459'
down_revision = '02af933f1976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet', sa.Column('pdf', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet', 'pdf')
    # ### end Alembic commands ###
